### ISSUE TITLE
Create_trainset error

### ISSUE THREAD

**Issue by Chengaowei** [LINCellularNeuroscience/VAME#40] opened 2021-03-24 16:57 UTC
Hi,
Thanks for your work. It's excellent!
I run the demo.py file.  And got an error at --'create_trainset'.

It says: 'ValueError: need at least one array to concatenate'
could you tell me how to fix it？
![image](https://user-images.githubusercontent.com/45705105/112351521-f08ba000-8d04-11eb-898d-3457ae70f90b.png)
![image](https://user-images.githubusercontent.com/45705105/112351799-2761b600-8d05-11eb-99ef-afcdaaa7ad8a.png)

**Comment by KLuxem** [comment] 2021-03-24 19:59
Hi,

I think this error appears because your config.yaml has no Data specified. Did you follow the VAME workflow [guide](https://github.com/LINCellularNeuroscience/VAME/wiki/1.-VAME-Workflow)?

What I see from the first image you attached is that your video folder name is wrong, you miss the video file format ending like .mp4 or .avi. The specification `videoType=.mp4` is not adding this to the string. Therefore, I believe your config.yaml is created wrongly and under the header _video_sets_ is no video name listed. Can you confirm this? 

If this is the case you need to re-initialize the project. Just delete the current one and create an new one with the right video path string.

I hope this helps!

**Comment by Chengaowei** [comment] 2021-03-25 07:11
Thanks for your quickly reply!  @KLuxem and sorry for this simple mistake.
I follow the workflow guide with your example video, and now get another error at 'vame.pose_segmentation(config)'
It says: 'Program is Terminated. Because you tried to allocate too many memory regions.'
![image](https://user-images.githubusercontent.com/45705105/112432797-56673e80-8d7c-11eb-8675-320548765b1a.png)

**Comment by KLuxem** [comment] 2021-03-25 08:34
So far I haven't seen this specific problem. Can you set a flag in the pose_segmentation [script](https://github.com/LINCellularNeuroscience/VAME/blob/master/vame/analysis/pose_segmentation.py)  at line 245 to see if the error occurs after the k-Means calculation? Just type something like `print("Flag")` so that we understand better where the program breaks for you.

**Comment by Chengaowei** [comment] 2021-03-25 09:18
Print-245
![print-245](https://user-images.githubusercontent.com/45705105/112449088-03968280-8d8e-11eb-8738-e745c66b6022.png)

Print-250
![print-250](https://user-images.githubusercontent.com/45705105/112449165-10b37180-8d8e-11eb-869e-f76429824de7.png)

**Comment by KLuxem** [comment] 2021-03-25 09:31
So your error seems related to BLAS. Are you using or have installed anything like Dask?
We could not reproduce this error on two different computer so far. .

Check out this thread:
https://stackoverflow.com/questions/45086246/too-many-memory-regions-error-with-dask

Maybe setting `export OMP_NUM_THREADS=1` could help.

**Comment by Chengaowei** [comment] 2021-03-25 10:51
I checked VAME envs, and  didn't find something like Dask~~
![image](https://user-images.githubusercontent.com/45705105/112460871-537b4680-8d9a-11eb-9e65-dad65c47a55e.png)

I want to try  'export OMP_NUM_THREADS=1'.  where should I do this?

AND I found a page here:
https://github.com/xianyi/OpenBLAS/wiki/faq#program-is-terminated-because-you-tried-to-allocate-too-many-memory-regions
![image](https://user-images.githubusercontent.com/45705105/112461205-af45cf80-8d9a-11eb-947e-f1f44321a93f.png)
Do you think this can help ?

**Comment by KLuxem** [comment] 2021-03-25 11:15
You should be able to type 'export OMP_NUM_THREADS=1' just in your console and try again. 

This issue seems to be more machine depended than on the VAME package.  Maybe updating the numpy version can help. 

What you could still check if is the Kmeans call in function `same_parameterization` at line 112 is working. Maybe set another flag in line 115 and line 123 to pin down where the error is happening. And another one at line 133. If you think its the Kmeans call for you try out the example from [sklearn](https://scikit-learn.org/stable/auto_examples/cluster/plot_kmeans_assumptions.html#sphx-glr-auto-examples-cluster-plot-kmeans-assumptions-py) and see if you run into similar problems

**Comment by Chengaowei** [comment] 2021-03-25 14:28
I changed another PC; and the error disappeared!
Anyway, it's working now. 

I'll go ahead with your example data.

**Comment by KLuxem** [comment] 2021-03-25 14:35
Perfect! I close this issue then! 
Enjoy the example ;)

**Closed by KLuxem** 2021-03-25 14:35 UTC
